// WARNING - DO NOT HAND-EDIT THIS FILE
// It is automatically generated by Tools/Versionizer
// each time the main software is rebuilt

#include "Game.h"

#define xstr(s) str(s)
#define str(s) #s
static VersionManager *currVersionManager = 0 ;

VersionManager *GetVersionManager ()
{
  if ( ! currVersionManager )
    currVersionManager = new VersionManager () ;
  return currVersionManager ;
}

VersionManager::VersionManager ()
{ currVersionManager = this ; }

VersionManager::~VersionManager ()
{ if ( currVersionManager == this ) currVersionManager = 0 ; }

int VersionManager::GetMajor() const { return 0 ; }
int VersionManager::GetMinor() const { return 0 ; }
int VersionManager::GetRevision() const { return 122 ; }
#ifdef DEBUG
bool VersionManager::isDebug () const { return true ; }
const char *VersionManager::GetName() const { return "0.0.0122-D" ; }
#else
bool VersionManager::isDebug () const { return false ; }
const char *VersionManager::GetName() const { return "0.0.0122" ; }
#endif
const char *VersionManager::GetBuildTime() const { return xstr(DATE) ; }

